# Generated by Django 5.2.7 on 2025-10-25 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_validation', '0001_initial'),
        ('work_for_earn', '0004_alter_work_category_alter_work_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workotp',
            name='sent_to',
        ),
        migrations.RemoveField(
            model_name='workotp',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='workotp',
            name='work_id',
        ),
        migrations.AddField(
            model_name='workotp',
            name='work',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_for_earn.work'),
        ),
    ]
