# Generated by Django 5.2.7 on 2025-10-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_for_earn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='mobile',
            new_name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='work',
            name='paid_to_admin',
        ),
        migrations.AlterField(
            model_name='work',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(default='Physical', max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='posted_by',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
